parameters:
#    application_application.example.class: Application\ApplicationBundle\Example

services:
#    application_application.example:
#        class: %application_application.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
